### ISSUE TITLE
Dashboard v2.1 - Epic

### ISSUE THREAD

**Issue by jcx120** [stellar/dashboard#276]
Epic for follow on modules:

- [ ] [Fee Module](https://github.com/stellar/dashboard/issues/273)
- [ ] [Transaction Module](https://github.com/stellar/dashboard/issues/274)
- [ ] [Ledger Module](https://github.com/stellar/dashboard/issues/275)
